# This is a basic workflow to help you get started with Actions

name: Deploy to GitHub Pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  
  # Triggers the workflow from preceding workflows in the chain
  workflow_call:
    secrets:
      EVIDENCE_SOURCE__BIGQUERY_CONNECTION__AUTHENTICATOR:
        required: true
      EVIDENCE_SOURCE__BIGQUERY_CONNECTION__CLIENT_EMAIL:
        required: true
      EVIDENCE_SOURCE__BIGQUERY_CONNECTION__LOCATION:
        required: true
      EVIDENCE_SOURCE__BIGQUERY_CONNECTION__PRIVATE_KEY:
        required: true
      EVIDENCE_SOURCE__BIGQUERY_CONNECTION__PROJECT_ID:
        required: true

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: 'reporting'

      - name: Install dependencies
        run: |
          cd reporting/
          npm install

      - name: Generate connection credentials
        run: |
          mkdir -p reporting/sources/bigquery_connection
          CLIENT_EMAIL_B64=$(echo -n "${{ secrets.EVIDENCE_SOURCE__BIGQUERY_CONNECTION__CLIENT_EMAIL }}" | base64 -w 0)
          PRIVATE_KEY_B64=$(echo -n "${{ secrets.EVIDENCE_SOURCE__BIGQUERY_CONNECTION__PRIVATE_KEY }}" | base64 -w 0)
          PROJECT_ID_B64=$(echo -n "${{ secrets.EVIDENCE_SOURCE__BIGQUERY_CONNECTION__PROJECT_ID }}" | base64 -w 0)
          
          cat > reporting/sources/bigquery_connection/connection.options.yaml << EOF
          client_email: $CLIENT_EMAIL_B64
          private_key: $PRIVATE_KEY_B64
          project_id: $PROJECT_ID_B64
          EOF

      - name: build
        env:
          BASE_PATH: './build/${{ github.event.repository.name }}'
        run: |
          cd reporting/
          npm run sources
          npm run build

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v5
        with:
          path: 'reporting/build/${{ github.event.repository.name }}/reporting'

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
